package com.siemens.krawal.krawalcloudmanager.db.query;

/**
 * 
 * DO NOT EDIT OR FORMAT THIS FILE
 */
public final class DBQueries {


	private DBQueries() {

	}

	public static final String VERIFY_PROJECT_TUPLE = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>" + 
			"													ASK { projects:%s ?a ?s }";

	public static final String VERIFY_USER_TUPLE = "prefix users: <http://www.siemens.com/krawalcloud/users/>" + 
			"											ASK { users:%s ?a ?s }";


	public static final String VERIFY_PROJECT_USER_ACCESS = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "		SELECT DISTINCT ?user "
			+ "			WHERE {"
			+ "				projects:%s projects:hasUser ?user ."
			+ "				?user  users:hasGid \"%s\" ^^xsd:string ."
			+ "			}";


	public static final String VERIFY_CR_PROJECT_USER_ACCESS = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "				SELECT DISTINCT ?latestRevisionNumber ?revisions ?user "
			+ "				WHERE{"
			+ "					projects:%s projects:hasUser ?user ;"
			+ "                             projects:hasLatestRevisionNumber ?latestRevisionNumber."
			+ " 			OPTIONAL{"
			+ "						projects:%s projects:hasRevision ?revisions . "
			+ "           			?revisions projects:hasCheckoutRevisionId \"%s\" ^^xsd:string ."
			+ "       			 }"
			+ "				?user  users:hasGid \"%s\" ^^xsd:string ."
			+ "			}";


	public static final String VERIFY_USER_ACCESS_PROJECT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+"prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "		SELECT DISTINCT ?user ?revision"
			+ "			 WHERE {"
			+ "				projects:%s projects:hasUser ?user ;"
			+ "							projects:hasRevision ?revision . "
			+ "				?user     users:hasGid \"%s\" ^^xsd:string ."
			+ "			    ?revision projects:hasCheckoutRevisionId \"%s\" ^^xsd:string ."
			+ "			}";

	public static final String DELETE_PROJECT = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>" 
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "		DELETE {"
			+ " 		projects:%s projects:hasRevision ?revisions . "
			+ " 		?revisions ?a ?b .  "
			+ " 		?b ?e ?f . "
			+ " 		projects:%s ?c ?d . "
			+ " 	}  "
			+ " 	WHERE{ "
			+ " 		projects:%s projects:hasRevision ?revisions . "
			+ " 		?revisions ?a ?b .  "
			+ " 		OPTIONAL {"
			+ "				?b ?e ?f ."
			+ " 			FILTER (?e != users:hasGid && ?e != users:hasUserName)"
			+ " 		} "
			+ " 		projects:%s ?c ?d . "
			+ " 	}";


	public static final String FETCH_USERS = "prefix users: <http://www.siemens.com/krawalcloud/users/> "
			+ "		SELECT DISTINCT ?user ?id "
			+ "		WHERE{"
			+ " 		?user users:hasGid ?id"
			+ " 		FILTER(?id in (%s))"
			+ " 	}";


	public static final String VERIFY_CHECKOUT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "	SELECT DISTINCT ?revision "
			+ "		WHERE{"
			+ " 		projects:%s projects:hasRevision ?revision ;"
			+ "						projects:hasUser	users:%s ."
			+ " 		?revision projects:hasCheckoutRevisionId \"%s\" ^^xsd:string ."
			+ "		}";

	public static final String VERIFY_COMMITTED_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?revision "
			+ "		WHERE{"
			+ "			projects:%s projects:hasRevision ?revision ;"
			+ "						projects:hasUser	 users:%s ."
			+ " 		?revision projects:hasRevisionNumber \"%d\" ."
			+ "		}";

	public static final String GET_PROJECT_INFO = " prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>  "
			+ " SELECT DISTINCT ?gid ?description ?lrNumber ?revisionNo ?checkoutRevisionId ?comment ?committedBy ?createdBy"
			+ " WHERE {projects:%s projects:hasUser users:%s;"
			+ "                    projects:hasLatestRevisionNumber ?lrNumber;"
			+ "                    projects:hasDescription ?description ;"
			+ "                    projects:createdBy ?createdBy;"
			+ "                    projects:hasUser ?user . "
			+ "        ?user users:hasGid ?gid ."
			+ "        OPTIONAL{projects:%s projects:hasRevision ?revisions ."
			+ "                 ?revisions  projects:hasRevisionNumber ?revisionNo ;"
			+ "                             projects:hasCheckoutRevisionId ?checkoutRevisionId ."
			+ "                }"
			+ "        OPTIONAL{?revisions projects:hasComment ?comment;"
			+ "							   projects:committedBy ?committedBy ."
			+ "					}"
			+ "       }";

	public static final String GET_ALL_PROJECTS = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "	SELECT DISTINCT ?projects "
			+ "		WHERE{"
			+ " 		?a projects:hasName ?projects ; "
			+ " 		   projects:hasUser users:%s ."
			+ " 	}";

	public static final String FIND_PROJECT_OBJECT_COUNTER = " prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ "	SELECT DISTINCT ?s ?objectCounter "
			+ "		WHERE {"
			+ "		 	projects:%s projects:hasObjectCounter  ?objectCounter"
			+ " 	}" ;

	public static final String UPDATE_PROJECT_COUNTER = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+ "	DELETE { "
			+ "		projects:%s projects:hasObjectCounter \"%d\"^^xsd:int ."
			+ "	}"
			+ " INSERT { "
			+ " 	projects:%s projects:hasObjectCounter \"%d\"^^xsd:int."
			+ "	}"
			+ " WHERE{"
			+ " 	projects:%s projects:hasObjectCounter \"%d\"^^xsd:int ."
			+ "}";

	public static final String FIND_AGGREGATES =" prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "  SELECT DISTINCT ?aggregate ?id "
			+ "		WHERE {"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		BIND ( \"%s\" as ?targetCRId )"
			+ "	 		projects:%s projects:hasRevision ?revision ; "
			+"                      projects:hasUser users:%s ."
			+ "	 		?revision projects:hasRevisionNumber ?revNum ; "
			+ "	 			      projects:hasCheckoutRevisionId ?crId; "
			+ "	 			      projects:created ?aggregate . "
			+ "  		?aggregate projects:hasId ?id ;"
			+ "	 				   rdfs:label ?f ."
			+ "			 FILTER NOT EXISTS { "
			+ "					?otherRevision projects:deleted ?aggregate ;"
			+ "                                projects:hasRevisionNumber ?revNum1 ; "
			+ "			            		   projects:hasCheckoutRevisionId ?crId1 ."
			+ "                    FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "                  } "
			+ "			  FILTER(((?revNum <=  ?targetRevisionNum  && ?revNum >  \"0\"  ) || ?crId = ?targetCRId ) && ?id in (%s) && ?f = \"%s\" ) "
			+ "	  } ";


	public static final String FETCH_AGGREGATES_CHECKOUT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?id ?type"
			+ "	 WHERE{"
			+ " 	bind ( \"%d\" as ?targetRevisionNum )"
			+ " 	bind ( \"%s\" as ?targetCRId )"
			+ " 	projects:%s projects:hasRevision ?revisions ;"
			+ "                 projects:hasUser users:%s ."
			+ " 	?revisions projects:hasRevisionNumber ?revNum ;"
			+ "  		   projects:hasCheckoutRevisionId ?crId ;" 
			+ "  		   projects:created ?objects ."
			+ "  	?objects projects:hasId ?id ;"
			+ "			  projects:hasType ?type ;"
			+ "           rdfs:label \"Aggregate\" ^^xsd:string ."
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?objects ;"
			+ "                           		 projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			 projects:hasCheckoutRevisionId ?crId1 ."
			+ "  				FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "   	} "	
			+ " FILTER(( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" ) || ?crId = ?targetCRId )"
			+ " }";


	public static final String FETCH_AGGREGATES_COMMITTED_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?id ?type"
			+ "	 WHERE{"
			+ " 	bind ( \"%d\" as ?targetRevisionNum )"
			+ " 	projects:%s projects:hasRevision ?revisions ;"
			+ "                 projects:hasUser users:%s ."
			+ " 	?revisions projects:hasRevisionNumber ?revNum ;"
			+ "  		   projects:created ?objects ."
			+ "  	?objects projects:hasId ?id ;"
			+ "			  projects:hasType ?type ;"
			+ "           rdfs:label \"Aggregate\" ^^xsd:string ."
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?objects ;"
			+ "                           		 projects:hasRevisionNumber ?revNum1 ; "
			+ "  				FILTER ( ?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\" )"                                         
			+ "   	} "	
			+ " FILTER( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" )"
			+ " }";

	public static final String FETCH_CONTROL_UNITS_CHECKOUT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>  "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " prefix lp: <http://www.siemens.com/krawalcloud/projects/%s/loadpoints/>"
			+ "	SELECT DISTINCT ?id ?type "
			+ "		WHERE{"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		BIND ( \"%s\" as ?targetCRId )"
			+ " 		projects:%s projects:hasRevision ?revisions ;"
			+ "                     projects:hasUser users:%s ."
			+ "		 	?revisions projects:hasRevisionNumber ?revNum ;"
			+ "  				   projects:hasCheckoutRevisionId ?crId ;"
			+ "  				   projects:created ?objects ."
			+ "  		?objects projects:hasId ?id ;"
			+ "			         projects:hasType ?type ;"
			+ "           		 rdfs:label \"ControlUnit\" ^^xsd:string ."
			+ " 		lp:%s  projects:%s ?objects ."
			+"  		FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?objects ;"
			+ "                           		 projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			 projects:hasCheckoutRevisionId ?crId1 ."
			+ "  				FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "   			} "	
			+ " 	FILTER(( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" ) || ?crId = ?targetCRId )"
			+ " 	}";

	public static final String FETCH_CONTROL_UNITS_COMMITTED_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>  "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " prefix lp: <http://www.siemens.com/krawalcloud/projects/%s/loadpoints/>"
			+ "	SELECT DISTINCT ?id ?type "
			+ "		WHERE{"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		projects:%s projects:hasRevision ?revisions ;"
			+ "                     projects:hasUser users:%s ."
			+ "		 	?revisions projects:hasRevisionNumber ?revNum ;"
			+ "  				   projects:created ?objects ."
			+ "  		?objects projects:hasId ?id ;"
			+ "			         projects:hasType ?type ;"
			+ "           		 rdfs:label \"ControlUnit\" ^^xsd:string ."
			+ " 		lp:%s  projects:%s ?objects ."
			+"  		FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?objects ;" 
			+ "                           		 projects:hasRevisionNumber ?revNum1 ; "
			+ "  				FILTER ( ?revNum1 <=  ?targetRevisionNum  && ?revNum1 >  \"0\")"                                         
			+ "   			} "	
			+ " 	FILTER( ?revNum <= \"%d\" && ?revNum > \"0\" )"
			+ " 	}";


	public static final String FETCH_SIGNAL_CONNECTIONS_CHECKOUT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " prefix lp: <http://www.siemens.com/krawalcloud/projects/%s/loadpoints/>"
			+ " SELECT DISTINCT ?id ?appliedToPort ?appliedViaPort ?valuesId ?valuesType ?valuesR  "
			+ "		WHERE{"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		BIND ( \"%s\" as ?targetCRId )"
			+ " 		projects:%s projects:hasRevision ?revisions ;"
			+ "						projects:hasRevision ?revisions2 ;"
			+ "                     projects:hasUser users:%s ."
			+ " 		?revisions  projects:hasRevisionNumber ?revNum ;"
			+ "  					projects:hasCheckoutRevisionId ?crId ;"
			+ "  					projects:created ?objects ."
			+ " 		?objects projects:hasId ?id ; "
			+ "           		 rdfs:label \"SignalConnection\" ^^xsd:string ;"
			+ "    				 projects:appliedToPort ?appliedToPort ; "
			+ "					 projects:appliedViaPort ?appliedViaPort ;" 
			+ "			 		 ?valuesR ?values ."
			+ " 		?revisions2 projects:hasRevisionNumber ?revNum2 ;"
			+ "  					projects:hasCheckoutRevisionId ?crId2 ;"
			+ "  					projects:created ?values ."
			+ "  		lp:%s 		projects:%s ?objects ."
			+ "  		?values projects:hasId ?valuesId ;" 
			+ "					rdfs:label ?valuesType. "
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?objects ;"
			+ "                           		 projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			 projects:hasCheckoutRevisionId ?crId1 ."
			+ "  				FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "  	 	} "	
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision2 projects:deleted ?values ;"
			+ "                           		 projects:hasRevisionNumber ?revNum3 ; "
			+ "			            			 projects:hasCheckoutRevisionId ?crId3 ."
			+ "  				FILTER ( ((?revNum3 <=  \"%d\"  && ?revNum3 >  \"0\"  ) || ?crId3 = \"%s\" ))"                                         
			+ "   		} "	
			+ " 	FILTER(( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" ) || ?crId = ?targetCRId )"
			+ " 	FILTER(( ?revNum2 <= ?targetRevisionNum && ?revNum2 > \"0\" ) || ?crId2 = ?targetCRId )"
			+ "  }";

	public static final String FETCH_SIGNAL_CONNECTIONS_COMMITTED_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " prefix lp: <http://www.siemens.com/krawalcloud/projects/%s/loadpoints/>"
			+ " SELECT DISTINCT ?id ?appliedToPort ?appliedViaPort ?valuesId ?valuesType ?valuesR  "
			+ "		WHERE{"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		projects:%s projects:hasRevision ?revisions ;"
			+ "						projects:hasRevision ?revisions2 ;"
			+ "                     projects:hasUser users:%s ."
			+ " 		?revisions  projects:hasRevisionNumber ?revNum ;"
			+ "  					projects:created ?objects ."
			+ " 		?objects projects:hasId ?id ; "
			+ "           		 rdfs:label \"SignalConnection\" ^^xsd:string ;"
			+ "    				 projects:appliedToPort ?appliedToPort ; "
			+ "					 projects:appliedViaPort ?appliedViaPort ;" 
			+ "			 		 ?valuesR ?values ."
			+ " 		?revisions2 projects:hasRevisionNumber ?revNum2 ;" 
			+ "  					projects:created ?values ."
			+ "  		lp:%s 		projects:%s ?objects ."
			+ "  		?values projects:hasId ?valuesId ;" 
			+ "					rdfs:label ?valuesType. "
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?objects ;"
			+ "                           		 projects:hasRevisionNumber ?revNum1 . "
			+ "  				FILTER ( ?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  )"                                         
			+ "  	 	} "	
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision2 projects:deleted ?values ;"
			+ "                           		 projects:hasRevisionNumber ?revNum3 . "
			+ "  				FILTER ( ?revNum3 <=  \"%d\"  && ?revNum3 >  \"0\" )"                                         
			+ "   		} "	
			+ " 	FILTER( ?revNum <= ?targetRevisionNum && ?revNum > \"0\"  )"
			+ " 	FILTER( ?revNum2 <= ?targetRevisionNum && ?revNum2 > \"0\"  )"
			+ "  }";

	public static final String FETCH_CONSTRAINTS_CHECKOUT_REVISION = " prefix projects: <http://www.siemens.com/krawalcloud/projects/>  "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " prefix loadpoint: <http://www.siemens.com/krawalcloud/projects/%s/loadpoints/>"
			+ " SELECT DISTINCT ?id ?type ?lpId "
			+ "		WHERE{"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ "			BIND ( \"%s\" as ?targetCRId )"
			+ " 		projects:%s projects:hasRevision ?revisions ;"
			+ "						projects:hasRevision ?revisions2 ;"
			+ "                     projects:hasUser users:%s ."
			+ " 		?revisions  projects:hasRevisionNumber ?revNum ;" 
			+ "			    		projects:hasCheckoutRevisionId ?crId ;"
			+ "  					projects:created ?objects ."
			+ " 		?revisions2 projects:hasRevisionNumber ?revNum3 ;" 
			+ "			    		projects:hasCheckoutRevisionId ?crId3 ."
			+ "  		?objects 	projects:hasId ?id ;"
			+ "			  			projects:hasType ?type ;"
			+ "           			rdfs:label \"Constraint\" ^^xsd:string ."
			+ "  		loadpoint:%s 		projects:%s ?objects . "
			+ "		OPTIONAL {"
			+ "			?objects 	projects:referencingTo ?lp ."
			+ " 		?lp 		projects:hasId ?lpId . "
			+ "			?revisions2 projects:created ?lp ."
			+"  		FILTER NOT EXISTS {"
			+ "					 ?otherRevision2 projects:deleted ?lp ;"
			+ "                           		 projects:hasRevisionNumber ?revNum2 ; "
			+ "			            			 projects:hasCheckoutRevisionId ?crId2 ."
			+ "  				FILTER ( (?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\" ) || ?crId2 = \"%s\" )"                                         
			+ "   			} "	
			+ "			}"
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?objects ;"
			+ "                           		 projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			 projects:hasCheckoutRevisionId ?crId1 ."
			+ "  				FILTER ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\" ) || ?crId1 = \"%s\")"                                         
			+ "   		} "	
			+ " 	FILTER( (?revNum <= ?targetRevisionNum && ?revNum > \"0\") || ?crId = ?targetCRId  )"
			+ " 	FILTER(( ?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" ) || ?crId3 = ?targetCRId )"
			+ " }";

	public static final String FETCH_CONSTRAINTS_COMMITTED_REVISION = " prefix projects: <http://www.siemens.com/krawalcloud/projects/>  "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " prefix loadpoint: <http://www.siemens.com/krawalcloud/projects/%s/loadpoints/>"
			+ " SELECT DISTINCT ?id ?type ?lpId "
			+ "		WHERE{"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		projects:%s projects:hasRevision ?revisions ;"
			+ "						projects:hasRevision ?revisions2 ;"
			+ "                     projects:hasUser users:%s ."
			+ " 		?revisions  projects:hasRevisionNumber ?revNum ;"
			+ "  					projects:created ?objects ."
			+ " 		?revisions2 projects:hasRevisionNumber ?revNum3 ."
			+ "  		?objects 	projects:hasId ?id ;"
			+ "			  			projects:hasType ?type ;"
			+ "           			rdfs:label \"Constraint\" ^^xsd:string ."
			+ "  		loadpoint:%s 		projects:%s ?objects . "
			+ "		OPTIONAL {"
			+ "			?objects 	projects:referencingTo ?lp ."
			+ " 		?lp 		projects:hasId ?lpId . "
			+ "			?revisions2 projects:created ?lp ."
			+"  		FILTER NOT EXISTS {"
			+ "					 ?otherRevision2 projects:deleted ?lp ;"
			+ "                           		 projects:hasRevisionNumber ?revNum2 . "
			+ "  				FILTER ( ?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  )"                                         
			+ "   			} "	
			+ "			}"
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?objects ;"
			+ "                           		 projects:hasRevisionNumber ?revNum1 . "
			+ "  				FILTER ( ?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\" )"                                         
			+ "   		} "	
			+ " 	FILTER( ?revNum <= ?targetRevisionNum && ?revNum > \"0\"  )"
			+ " 	FILTER( ?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" )"
			+ " }";


	public static final String FETCH_CONNECTIONS_CHECKOUT_REVISION = " prefix projects: <http://www.siemens.com/krawalcloud/projects/>  "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?id ?sourceAggregateId ?targetAggregateId ?type ?sourcePort ?targetPort "
			+ "	WHERE{"
			+ "		 BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 	 BIND ( \"%s\" as ?targetCRId )"
			+ " 	projects:%s 	projects:hasRevision ?revisions ;"
			+ "						projects:hasRevision ?revisions2 ;"
			+ "                     projects:hasUser users:%s ."
			+ " 	?revisions 		projects:hasRevisionNumber ?revNum ;"
			+ " 			  		projects:hasCheckoutRevisionId ?crId ;"
			+ " 			  		projects:created ?objects ."
			+ " 	?objects 		projects:via ?aggregate ;"
			+ "        		 		projects:hasType ?type;"
			+ "         	 		projects:ingresPort ?sourcePort;"
			+ "       		 		projects:hasId ?id ;"
			+ "			 	 		rdfs:label \"MediumConnection\" ^^xsd:string ."
			+ " 	?revisions2 	projects:hasRevisionNumber ?revNum3 ;"
			+ " 					projects:hasCheckoutRevisionId ?crId3 ;"
			+ " 					projects:created ?aggregate . "
			+ " 	?aggregate 		projects:hasId ?sourceAggregateId ."

			+ "		 OPTIONAL {"
			+ "				 ?e 	projects:via ?objects ;"
			+ "           			rdfs:label \"Aggregate\" ^^xsd:string;"
			+ "						projects:hasId ?targetAggregateId . "
			+ "				?objects projects:outgresport ?targetPort . "	
			+ " 	}"
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?objects ;"
			+ "                           		 projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			 projects:hasCheckoutRevisionId ?crId1 ."
			+ "  				FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "  	 } "	
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision2 projects:deleted ?aggregate ;"
			+ "                           		 projects:hasRevisionNumber ?revNum2 ; "
			+ "			            			 projects:hasCheckoutRevisionId ?crId2 ."
			+ "  				FILTER ( ((?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  ) || ?crId2 = \"%s\" ))"                                         
			+ "  	 } "	
			+ " 	FILTER ((?revNum <= ?targetRevisionNum && ?revNum > \"0\" ) || ?crId = ?targetCRId )"
			+ " 	FILTER ((?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" ) || ?crId3 = ?targetCRId)"
			+ " }";

	public static final String FETCH_CONNECTIONS_COMMITTED_REVISION = " prefix projects: <http://www.siemens.com/krawalcloud/projects/>  "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?id ?sourceAggregateId ?targetAggregateId ?type ?sourcePort ?targetPort "
			+ "	WHERE{"
			+ "		 BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 	projects:%s 	projects:hasRevision ?revisions ;"
			+ "						projects:hasRevision ?revisions2 ;"
			+ " 					projects:hasUser users:%s ."
			+ " 	?revisions 		projects:hasRevisionNumber ?revNum ;"
			+ " 			  		projects:created ?objects ."
			+ " 	?objects 		projects:via ?aggregate ;"
			+ "        		 		projects:hasType ?type;"
			+ "         	 		projects:ingresPort ?sourcePort;"
			+ "       		 		projects:hasId ?id ;"
			+ "			 	 		rdfs:label \"MediumConnection\" ^^xsd:string ."
			+ " 	?revisions2 	projects:hasRevisionNumber ?revNum3 ;"
			+ " 					projects:created ?aggregate . "
			+ " 	?aggregate 		projects:hasId ?sourceAggregateId ."
			+ "		 OPTIONAL {"
			+ "				 ?e 	projects:via ?objects ;"
			+ "           			rdfs:label \"Aggregate\" ^^xsd:string;"
			+ "						projects:hasId ?targetAggregateId . "
			+ "				?objects projects:outgresport ?targetPort ."	
			+ " 	}"
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?objects ;"
			+ "                           		 projects:hasRevisionNumber ?revNum1 . "
			+ "  				FILTER ( ?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  )"                                         
			+ "  	 } "	
			+"  	FILTER NOT EXISTS {"
			+ "					 ?otherRevision2 projects:deleted ?aggregate ;"
			+ "                           		 projects:hasRevisionNumber ?revNum2 . "
			+ "  				FILTER ( ?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\" )"                                         
			+ "  	 } "	
			+ " 	FILTER ( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" )"
			+ " 	FILTER ( ?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" )"
			+ " }";

	public static final String FETCH_CYCLE_SEGMENT_CHECKOUT_REVISION = " prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?id ?aggregateId "
			+ "	WHERE{"
			+ "		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 	BIND ( \"%s\" as ?targetCRId )"
			+ " 	projects:%s projects:hasRevision ?revisions ;"
			+ "					projects:hasRevision ?revisions2 ;"
			+ "                 projects:hasUser users:%s ."
			+ " 	?revisions  projects:hasRevisionNumber ?revNum ;"
			+ " 				projects:hasCheckoutRevisionId ?crId ;"
			+ " 			 	projects:created ?objects ."
			+ " 	?objects 	projects:hasCycleSegmentAssociation ?csa ."
			+ " 	?revisions2 projects:hasRevisionNumber ?revNum4 ;"
			+ " 				projects:hasCheckoutRevisionId ?crId4 ;"
			+ " 				projects:created ?csa ."
			+ " 	?objects    projects:hasId ?id ;"
			+ " 				rdfs:label \"CycleSegment\" ^^xsd:string ."
			+ "		?csa 		projects:contains ?aggregates ;"
			+ "		 			rdfs:label \"CycleSegmentAssociation\" ^^xsd:string ."
			+ " 	?aggregates projects:hasId ?aggregateId ;"
			+ "					rdfs:label \"Aggregate\" ^^xsd:string ."			
			+"  	FILTER NOT EXISTS { "
			+ "						?otherRevision1 projects:deleted ?objects ;"
			+ "                            			projects:hasRevisionNumber ?revNum1 ; " 
			+ "			            				projects:hasCheckoutRevisionId ?crId1 ."
			+ " 					 FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "   	} "	
			+"  	FILTER NOT EXISTS { "
			+ "						?otherRevision2 projects:deleted ?csa ;"
			+ "                            			projects:hasRevisionNumber ?revNum2 ; "
			+ "			            				projects:hasCheckoutRevisionId ?crId2 ."
			+ " 					 FILTER ( ((?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  ) || ?crId2 = \"%s\" ))"                                         
			+ "  	 } "
			+ "		FILTER(( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" )|| ?crId = ?targetCRId )"
			+ "		FILTER((?revNum4 <= ?targetRevisionNum && ?revNum4 > \"0\" )|| ?crId4 = ?targetCRId)"
			+ " }";


	public static final String FETCH_CYCLE_SEGMENT_COMMITTED_REVISION = " prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?id ?aggregateId "
			+ "	WHERE{"
			+ "		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 	projects:%s projects:hasRevision ?revisions ;"
			+ "					projects:hasRevision ?revisions2 ;"
			+ "                 projects:hasUser users:%s ."
			+ " 	?revisions  projects:hasRevisionNumber ?revNum ;"
			+ " 			 	projects:created ?objects ."
			+ " 	?objects 	projects:hasCycleSegmentAssociation ?csa ."
			+ " 	?revisions2 projects:hasRevisionNumber ?revNum4 ;"
			+ " 				projects:created ?csa ."
			+ " 	?objects    projects:hasId ?id ;"
			+ " 				rdfs:label \"CycleSegment\" ^^xsd:string ."
			+ "		?csa 		projects:contains ?aggregates ;"
			+ "		 			rdfs:label \"CycleSegmentAssociation\" ^^xsd:string ."
			+ " 	?aggregates projects:hasId ?aggregateId ;"
			+ "					rdfs:label \"Aggregate\" ^^xsd:string ."			
			+"  	FILTER NOT EXISTS { "
			+ "						?otherRevision1 projects:deleted ?objects ;"
			+ "                            			projects:hasRevisionNumber ?revNum1 . "
			+ " 					 FILTER ( ?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\" )"                                         
			+ "   	} "	
			+"  	FILTER NOT EXISTS { "
			+ "						?otherRevision2 projects:deleted ?csa ;"
			+ "                            			projects:hasRevisionNumber ?revNum2 . "
			+ " 					 FILTER ( ?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\" )"                                         
			+ "  	 } "
			+ "		FILTER( ?revNum <= ?targetRevisionNum && ?revNum > \"0\"  )"
			+ "		FILTER( ?revNum4 <= ?targetRevisionNum && ?revNum4 > \"0\" )"
			+ " }";


	public static final String FETCH_CYCLE_SEGMENT_CHECKOUT_REVISION_ID = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>  "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?objects ?d "
			+ "	WHERE{"
			+ " 	BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 	BIND ( \"%s\" as ?targetCRId )"
			+ " 	projects:%s projects:hasRevision ?revisions ;"
			+ "					projects:hasRevision ?revisions2 ;"
			+ "                 projects:hasUser users:%s ."
			+ " 	?revisions 	projects:hasRevisionNumber ?revNum ;"
			+ " 			 	projects:hasCheckoutRevisionId ?crId ;"
			+ " 			 	projects:created ?objects ."
			+ " 	?objects 	?s ?d ."
			+ " 	?revisions2 projects:hasRevisionNumber ?revNum3 ;"
			+ " 				projects:hasCheckoutRevisionId ?crId3 ;"
			+ " 			 	projects:created ?d ."
			+ " 	?objects 	rdfs:label ?f ."
			+ " 	?objects 	projects:hasId \"%d\" ^^xsd:int."
			+"  	FILTER NOT EXISTS { "
			+ "					?otherRevision1 projects:deleted ?objects ;"
			+ "                            		projects:hasRevisionNumber ?revNum1 ; "
			+ "			            		    projects:hasCheckoutRevisionId ?crId1 ."
			+ " 					 FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "  	 } "	
			+" 	  	FILTER NOT EXISTS { "
			+ "					?otherRevision2 projects:deleted ?d ;"
			+ "                             	projects:hasRevisionNumber ?revNum2 ; "
			+ "			            	 		<http://www.siemens.com/krawalcloud/projects/hasCheckoutRevisionId> ?crId2 ."
			+ " 				FILTER ( ((?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  ) || ?crId2 = \"%s\" ))"                                         
			+ "   	} "
			+ " 	FILTER(((?revNum <= ?targetRevisionNum && ?revNum > \"0\" )|| ?crId = ?targetCRId) && ?f = \"%s\")"
			+ " 	FILTER((?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" )|| ?crId3 = ?targetCRId)"
			+ " }";

	public static final String FETCH_LOADPOINTS_CHECKOUT_REVISION =  "prefix projects: <http://www.siemens.com/krawalcloud/projects/>   "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?id "
			+ "		WHERE{"
			+ "			BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		BIND ( \"%s\" as ?targetCRId )"
			+ " 		projects:%s projects:hasRevision ?revisions ;"
			+ "                     projects:hasUser users:%s ."					
			+ " 		?revisions 	 projects:hasRevisionNumber ?revNum ;"
			+ " 					 projects:hasCheckoutRevisionId ?crId ;"
			+ " 					 projects:created ?objects ."
			+ " 		?objects 	 projects:hasId ?id ;"
			+ " 					 rdfs:label \"Loadpoint\" ^^xsd:string ."		
			+"  		FILTER NOT EXISTS { "
			+ "						?otherRevision  projects:deleted ?objects ;"
			+ "                            			projects:hasRevisionNumber ?revNum1 ; "
			+ "			            				projects:hasCheckoutRevisionId ?crId1 ."
			+ " 					 FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "   		} "	
			+ " 	FILTER((?revNum <= ?targetRevisionNum && ?revNum > \"0\" )|| ?crId = ?targetCRId)"
			+ " 	}";

	public static final String FETCH_LOADPOINTS_COMMITTED_REVISION =  "prefix projects: <http://www.siemens.com/krawalcloud/projects/>   "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?id "
			+ "		WHERE{"
			+ "			BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		projects:%s projects:hasRevision ?revisions ;"
			+ "                     projects:hasUser users:%s ."
			+ " 		?revisions 	 projects:hasRevisionNumber ?revNum ;"
			+ " 					 projects:created ?objects ."
			+ " 		?objects 	 projects:hasId ?id ;"
			+ " 					 rdfs:label \"Loadpoint\" ^^xsd:string ."		
			+"  		FILTER NOT EXISTS { "
			+ "						?otherRevision  projects:deleted ?objects ;"
			+ "                            			projects:hasRevisionNumber ?revNum1 . "
			+ " 					 FILTER ( ?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\" )"                                         
			+ "   		} "	
			+ " 	FILTER( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" )"
			+ " 	}";


	public static final String FIND_OBJECT = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?lp "
			+ "	WHERE {"
			+ " 	BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 	BIND ( \"%s\" as ?targetCRId )"
			+ " 	projects:%s projects:hasRevision ?revision ;"
			+ "                 projects:hasUser users:%s ."
			+ " 	?revision   projects:hasRevisionNumber ?revNum;"
			+ "     			projects:hasCheckoutRevisionId ?crId ; "
			+ "     			projects:created ?lp . "
			+ " 	?lp 		projects:hasId \"%d\" ^^xsd:int ;"
			+ " 		 		rdfs:label ?label ."
			+ " 	 	FILTER NOT EXISTS {"
			+ "					 ?otherRevision1 projects:deleted ?lp ; "
			+ "                           		 projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			 projects:hasCheckoutRevisionId ?crId1 ."
			+ "  				FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "   } "		
			+ " 	FILTER((( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" ) || ?crId = ?targetCRId ) && ?label = \"%s\")"
			+ "}";

	public static final String FETCH_AGGREGATE_ASSOCIATION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?objects ?d "
			+ "	WHERE{"
			+ " 	BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 	BIND ( \"%s\" as ?targetCRId )"
			+ " 	projects:%s 	projects:hasRevision ?revisions ;"
			+ "						projects:hasRevision ?revisions2 ;"
			+ "                     projects:hasUser users:%s ."
			+ " 	?revisions 	projects:hasRevisionNumber ?revNum ;"
			+ " 			 	projects:hasCheckoutRevisionId ?crId ;"
			+ " 			 	projects:created ?objects ."
			+ " 	?revisions2 projects:hasRevisionNumber ?revNum3 ;"
			+ " 			 	projects:hasCheckoutRevisionId ?crId3 ."
			+ " 	?objects rdfs:label \"Aggregate\" ^^xsd:string ."
			+ " 	?objects projects:hasId \"%d\" ^^xsd:int."
			+ " 	OPTIONAL { "
			+ "				?objects projects:hasAssemblyAssociation ?d . "
			+ " 			?revisions2 projects:created ?objects ."
			+"  			FILTER NOT EXISTS { "
			+ "						?otherRevision1 projects:deleted ?d ;" 
			+ "                            		projects:hasRevisionNumber ?revNum2 ; "
			+ "			            			projects:hasCheckoutRevisionId ?crId2 ."
			+ " 					 FILTER ( ((?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  ) || ?crId2 = \"%s\" ))"                                         
			+ "   					} "
			+ "			}"
			+"  	FILTER NOT EXISTS { "
			+ "						?otherRevision2 projects:deleted ?objects ;"
			+ "                            		projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			projects:hasCheckoutRevisionId ?crId1 ."
			+ " 					 FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "   			} "	

			+ " 	FILTER((?revNum <= ?targetRevisionNum && ?revNum > \"0\" )|| ?crId = ?targetCRId)"
			+ " 	FILTER((?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" )|| ?crId3 = ?targetCRId)"
			+ " }";

	public static final String FETCH_ASSEMBLY_PARTS_CHECKOUT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?id "
			+ " WHERE{"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		BIND ( \"%s\" as ?targetCRId )"
			+ " 		projects:%s projects:hasRevision ?revisions ;"
			+ "						projects:hasRevision ?revisions2 ;"
			+ "                     projects:hasUser users:%s ."
			+ " 		?revisions  projects:hasRevisionNumber ?revNum ;"
			+ " 			 		projects:hasCheckoutRevisionId ?crId ; "
			+ " 			 		projects:created ?objects ."
			+ " 		?objects 	rdfs:label \"Aggregate\" ^^xsd:string ;"
			+ " 			 		projects:hasId \"%d\" ^^xsd:int;"
			+ " 					projects:hasAssemblyAssociation ?d . "
			+ " 		?revisions2 projects:hasRevisionNumber ?revNum4 ;"
			+ " 			 		projects:hasCheckoutRevisionId ?crId4 ;"
			+ " 			 		projects:created ?d ."
			+ " 		?d 			projects:isPartOf ?g ."
			+ " 		?g 			projects:hasId ?id ."
			+ "  		FILTER NOT EXISTS { "
			+ "						?otherRevision1 projects:deleted ?d ;"
			+ "                            			projects:hasRevisionNumber ?revNum2 ; "
			+ "			            				projects:hasCheckoutRevisionId ?crId2 ."
			+ " 					 FILTER ( ((?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  ) || ?crId2 = \"%s\" ))"                                         
			+ "  			 } "
			+ "  		FILTER NOT EXISTS { "
			+ "						?otherRevision2 projects:deleted ?objects ;"
			+ "                            			projects:hasRevisionNumber ?revNum1 ; "
			+ "			            				projects:hasCheckoutRevisionId ?crId1 ."
			+ " 					 FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "  			 } "	
			+ " 		FILTER((?revNum <= ?targetRevisionNum && ?revNum > \"0\" )|| ?crId = ?targetCRId )"
			+ " 		FILTER((?revNum4 <= ?targetRevisionNum && ?revNum4 > \"0\" )|| ?crId4 = ?targetCRId)"
			+ " 	}";


	public static final String FETCH_ASSEMBLY_PARTS_COMMITTED_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?id "
			+ " WHERE{"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		projects:%s projects:hasRevision ?revisions ;"
			+ "						projects:hasRevision ?revisions2 ;"
			+ "                     projects:hasUser users:%s ."
			+ " 		?revisions  projects:hasRevisionNumber ?revNum ;"
			+ " 			 		projects:created ?objects ."
			+ " 		?objects 	rdfs:label ?f ;"
			+ " 			 		projects:hasId \"%d\" ^^xsd:int;"
			+ " 					projects:hasAssemblyAssociation ?d . "
			+ " 		?revisions2 projects:hasRevisionNumber ?revNum4 ;"
			+ " 			 		projects:created ?d ."
			+ " 		?d 			projects:isPartOf ?g ."
			+ " 		?g 			projects:hasId ?id ."
			+"  		FILTER NOT EXISTS { "
			+ "						?otherRevision1 projects:deleted ?d ;"
			+ "                            			projects:hasRevisionNumber ?revNum2 . "
			+ " 					 FILTER ( ?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\" )"                                         
			+ "  			 } "
			+"  		FILTER NOT EXISTS { "
			+ "						?otherRevision2 projects:deleted ?objects ;"
			+ "                            			projects:hasRevisionNumber ?revNum1 . "
			+ " 					 FILTER ( ?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\" )"                                         
			+ "  			 } "	
			+ " 		FILTER((?revNum <= ?targetRevisionNum && ?revNum > \"0\" ) && ?f = \"Aggregate\")"
			+ " 		FILTER( ?revNum4 <= ?targetRevisionNum && ?revNum4 > \"0\" )"
			+ " 	}";


	public static final String FIND_OBJECTS_TO_DELETE = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?object ?b  (count(?object)as ?count)"
			+ " WHERE {	"
			+ "  	projects:%s projects:hasRevision ?revision ;"
			+ "					  projects:hasUser users:%s ."
			+ " 	?revision 	  projects:hasRevisionNumber ?revNum;"
			+ "          	  	  projects:hasCheckoutRevisionId ?crId;"
			+ "                   ?relation ?object ."
			+ "  	?object       projects:hasId \"%d\"^^xsd:int ;"
			+ "         	      rdfs:label \"%s\"^^xsd:string ;"
			+ "       		      ?a ?b ."
			+ "   FILTER(( ?relation = projects:deleted || ?relation = projects:created) "
			+ "   && ((?revNum <= \"%d\" && ?revNum > \"0\" ) || ?crId = \"%s\")) "
			+ "  }"
			+ " GROUP BY ?object ?b";


	public static final String FIND_PROJECT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " SELECT ?revNum "
			+ "	WHERE{	"
			+ " 	projects:%s projects:hasLatestRevisionNumber ?revNum .  "
			+ " }";

	public static final String COMMIT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+ " prefix revisions: <http://www.siemens.com/krawalcloud/projects/%s/revisions/> "
			+ " DELETE{    "
			+ "		projects:%s 	projects:hasLatestRevisionNumber \"%d\" ^^xsd:int ."
			+ "		revisions:%s 	projects:hasCheckoutRevisionId \"%s\" ^^xsd:string ;  "
			+ "       				projects:hasRevisionNumber \"%d\" ^^xsd:int ."
			+ "	}"
			+ "	INSERT{	"
			+ " 	projects:%s		 projects:hasLatestRevisionNumber \"%d\" ^^xsd:int ."
			+ " 	revisions:%s	 projects:hasRevisionNumber \"%d\" ;"
			+ "     				 projects:hasCheckoutRevisionId \"\" ^^xsd:string .  "
			+ "	}"
			+ "	WHERE{	"
			+ "		projects:%s 	projects:hasName \"%s\" ^^xsd:string ;     "
			+ "     				projects:hasRevision revisions:%s ;     "
			+ "     				projects:hasLatestRevisionNumber \"%d\" ^^xsd:int ."
			+ "  	revisions:%s	projects:hasCheckoutRevisionId \"%s\" ^^xsd:string ;"
			+ "     				projects:hasRevisionNumber \"%d\" ^^xsd:int ."
			+ "	}";

	public static final String DELETE_NODES = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>" 
			+ "DELETE { " 
			+ " 	?revision projects:created ?objects ;" 
			+"             	  projects:deleted ?objects ." 
			+"  	?objects ?x ?y ."  
			+" } "  
			+" WHERE { " 
			+"  		projects:%s projects:hasRevision ?revision . "  
			+"  		?revision 	projects:hasCheckoutRevisionId \"%s\" ^^xsd:string ;" 
			+"            		projects:created ?objects ;" 
			+"            		projects:deleted ?objects ." 
			+"  		?objects ?x ?y ."  
			+" }";
	public static final String DELETE_CHECKOUT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " 	DELETE{"
			+ " 		?revisions ?relations ?objects"
			+ "		}"
			+ " 	WHERE{"
			+ " 		projects:%s projects:hasRevision ?revisions ."
			+ " 		?revisions projects:hasCheckoutRevisionId \"%s\" ^^xsd:string ;"
			+ " 				   ?relations ?objects ."
			+ " 	}";


	public static final String FIND_DATA_OBJECT_ID = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT ?object ?data "
			+ "	WHERE {"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		BIND ( \"%s\" as ?targetCRId )"
			+ " 		projects:%s projects:hasRevision ?revision ;"
			+ "						projects:hasRevision ?revision2 ;"
			+"                      projects:hasUser users:%s ."
			+ " 		?revision 	projects:hasRevisionNumber ?revNum;"
			+ "          			projects:hasCheckoutRevisionId ?crId;"
			+ "           			projects:created ?object . "
			+ " 	    ?revision2 	projects:hasRevisionNumber ?revNum3;"
			+ "          			projects:hasCheckoutRevisionId ?crId3."
			+ " 		?object		projects:hasId \"%d\" ^^xsd:int ;"
			+ "    			 		rdfs:label \"%s\"^^xsd:string ."
			+ " 		OPTIONAL { "
			+ "						?object    projects:%s ?data . "
			+ "						?revision2 projects:created ?data ."
			+"  					FILTER NOT EXISTS {"
			+ "					 		?otherRevision1 projects:deleted ?data ;"
			+ "                           		 		projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			 		projects:hasCheckoutRevisionId ?crId1 ."
			+ "  						FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "   					} "				
			+ "					}"
			+"  		FILTER NOT EXISTS {"
			+ "					 	?otherRevision2 projects:deleted ?object ;"
			+ "                           		 	projects:hasRevisionNumber ?revNum2 ; "
			+ "			            			 	projects:hasCheckoutRevisionId ?crId2 ."
			+ "  					FILTER ( ((?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  ) || ?crId2 = \"%s\" ))"                                         
			+ "   				} "

			+ " 		FILTER(( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" )|| ?crId = ?targetCRId )"
			+ " 		FILTER(( ?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" )|| ?crId3 = ?targetCRId )"
			+ "}";



	public static final String FIND_LP_DATA_OBJECT_ID = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " prefix loadpoint: <http://www.siemens.com/krawalcloud/projects/%s/loadpoints/>"
			+ " SELECT ?object ?data "
			+ "		WHERE {   "
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		BIND ( \"%s\" as ?targetCRId )"
			+ " 		projects:%s 	projects:hasRevision ?revision ;"
			+ "							projects:hasRevision ?revision2 ;    "
			+ "                         projects:hasUser users:%s ."
			+ " 		?revision 		projects:hasRevisionNumber ?revNum;  "
			+ "           				projects:hasCheckoutRevisionId ?crId;"
			+ "           				projects:created ?object .   "
			+ " 		?revision2 		projects:hasRevisionNumber ?revNum3;             "
			+ "          				projects:hasCheckoutRevisionId ?crId3 ."
			+ " 		?object			projects:hasId \"%d\" ^^xsd:int ;"
			+ "    			 			rdfs:label \"%s\"^^xsd:string ."
			+ "			OPTIONAL {"
			+ "   				?object				projects:hasLoadData ?data .    "
			+ "   				loadpoint:%s		projects:belongsTo ?data .   "
			+ "   				?revision2  projects:created ?data .  "
			+"  				FILTER NOT EXISTS {"
			+ "					 		?otherRevision1 projects:deleted ?data ;"
			+ "                           		 		projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			 		projects:hasCheckoutRevisionId ?crId1 ."
			+ "  						FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "   					} "
			+ " 				}     "
			+"  		FILTER NOT EXISTS {"
			+ "					 ?otherRevision2 		projects:deleted ?object ;"
			+ "                           		 		projects:hasRevisionNumber ?revNum2 ; "
			+ "			            			 		projects:hasCheckoutRevisionId ?crId2 ."
			+ "  				FILTER ( ((?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  ) || ?crId2 = \"%s\" ))"                                         
			+ "   				} "
			+ " 		FILTER(( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" )|| ?crId = ?targetCRId )"
			+ " 		FILTER(( ?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" )|| ?crId3 = ?targetCRId )"
			+ " 	}";

	public static final String FIND_DATA_CHECKOUT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?data ?relation ?literalValue"
			+ "	WHERE {"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		BIND ( \"%s\" as ?targetCRId )"
			+ " 		projects:%s projects:hasRevision ?revision ;"
			+ "						projects:hasRevision ?revision2 ;"
			+ "                     projects:hasUser users:%s ."
			+ " 		?revision 	projects:hasRevisionNumber ?revNum;"
			+ "           			projects:hasCheckoutRevisionId ?crId;"
			+ "           			projects:created ?object . "
			+ " 		?object 	projects:hasId \"%d\" ^^xsd:int ;"
			+ "  					projects:%s ?data ;"
			+ "						rdfs:label \"%s\"^^xsd:string   ."
			+ "			?data 		rdfs:label \"%s\" ^^xsd:string ;"
			+ "						?relation 	?literalValue ."
			+ " 		?revision2 	projects:hasRevisionNumber ?revNum3;"
			+ "           			projects:hasCheckoutRevisionId ?crId3;"
			+ " 					projects:created ?data ."
			+"  		FILTER NOT EXISTS {"
			+ "					 	?otherRevision1 projects:deleted ?data ;"
			+ "                           		 	projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			 	projects:hasCheckoutRevisionId ?crId1 ."
			+ "  					FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "   				} "		
			+"  		FILTER NOT EXISTS {"
			+ "					 	?otherRevision2 projects:deleted ?object ;"
			+ "                           		 	projects:hasRevisionNumber ?revNum2 ; "
			+ "			            				projects:hasCheckoutRevisionId ?crId2 ."
			+ "  				FILTER ( ((?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  ) || ?crId2 = \"%s\" ))"                                         
			+ "  			 } "
			+ " 		FILTER(( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" )|| ?crId = ?targetCRId )"
			+ " 		FILTER(( ?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" )|| ?crId3 = ?targetCRId )"
			+ "}";

	public static final String FIND_DATA_COMMITTED_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " SELECT DISTINCT ?data ?relation ?literalValue "
			+ "	WHERE {"
			+ " 		BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		projects:%s projects:hasRevision ?revision ;"
			+ "						projects:hasRevision ?revision2 ;"
			+ "                     projects:hasUser users:%s ."
			+ " 		?revision 	projects:hasRevisionNumber ?revNum;"
			+ "           			projects:created ?object . "
			+ " 		?object 	projects:hasId \"%d\" ^^xsd:int ;"
			+ "  					projects:%s ?data ;"
			+ "						rdfs:label \"%s\"^^xsd:string   ."
			+ "			?data 		rdfs:label \"%s\" ^^xsd:string ;"
			+ "						?relation 	?literalValue ."
			+ " 		?revision2 	projects:hasRevisionNumber ?revNum3;"
			+ " 					projects:created ?data ."
			+"  		FILTER NOT EXISTS {"
			+ "					 	?otherRevision1 projects:deleted ?data ;"
			+ "                           		 	projects:hasRevisionNumber ?revNum1 . "
			+ "  					FILTER ( ?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\")"                                         
			+ "   				} "		
			+"  		FILTER NOT EXISTS {"
			+ "					 	?otherRevision2 projects:deleted ?object ;"
			+ "                           		 	projects:hasRevisionNumber ?revNum2 . "
			+ "  				FILTER ( ?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\")"                                         
			+ "  			 } "
			+ " 		FILTER( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" )"
			+ " 		FILTER( ?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" )"
			+ "}";

	public static final String FIND_LP_DATA_CHECKOUT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " prefix loadpoint: <http://www.siemens.com/krawalcloud/projects/%s/loadpoints/>"
			+ " SELECT DISTINCT ?data ?relation ?literalValue "
			+ "	WHERE {   "
			+ "		 	BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		BIND ( \"%s\" as ?targetCRId )"
			+ " 		projects:%s  projects:hasRevision ?revision ;"
			+ "						 projects:hasRevision ?revision2 ;   "
			+ "                      projects:hasUser users:%s ."
			+ " 		?revision 	 projects:hasRevisionNumber ?revNum;   "
			+ "         			 projects:hasCheckoutRevisionId ?crId;         "
			+ "         			 projects:created ?object .  "
			+ " 		?object		 projects:hasId \"%d\" ^^xsd:int ;   		 "
			+ "         			 projects:hasLoadData ?data ;"
			+ "						 rdfs:label \"%s\"^^xsd:string  . "
			+ " 		loadpoint:%s projects:belongsTo ?data ."
			+ "			?data 		 rdfs:label \"%s\" ^^xsd:string ;"
			+ "						 ?relation 	?literalValue ."
			+ " 		?revision2	 projects:hasRevisionNumber ?revNum3;   "
			+ "         			 projects:hasCheckoutRevisionId ?crId3;         "
			+ "         			 projects:created ?data ;   "  
			+"  		FILTER NOT EXISTS {"
			+ "					 		?otherRevision1 projects:deleted ?data ;"
			+ "                           		 		projects:hasRevisionNumber ?revNum1 ; "
			+ "			            			 		projects:hasCheckoutRevisionId ?crId1 ."
			+ "  						FILTER ( ((?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\"  ) || ?crId1 = \"%s\" ))"                                         
			+ "   		} "		
			+"  		FILTER NOT EXISTS {"
			+ "					 		?otherRevision2 projects:deleted ?object ;"
			+ "                           		 		projects:hasRevisionNumber ?revNum2 ; "
			+ "			            			 		projects:hasCheckoutRevisionId ?crId2 ."
			+ "  						FILTER ( ((?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  ) || ?crId2 = \"%s\" ))"                                         
			+ "   		} "
			+ " 		FILTER(( ?revNum <= ?targetRevisionNum && ?revNum > \"0\" )|| ?crId = ?targetCRId )"
			+ " 		FILTER(( ?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" )|| ?crId3 = ?targetCRId )"
			+ "}";

	public static final String FIND_LP_DATA_COMMITTED_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/> "
			+ " prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " prefix loadpoint: <http://www.siemens.com/krawalcloud/projects/%s/loadpoints/>"
			+ " SELECT DISTINCT ?data ?relation ?literalValue "
			+ "		WHERE {   "
			+ "		 	BIND ( \"%d\" as ?targetRevisionNum )"
			+ " 		projects:%s  projects:hasRevision ?revision ;"
			+ "						 projects:hasRevision ?revision2 ;   "
			+ "                      projects:hasUser users:%s ."
			+ " 		?revision 	 projects:hasRevisionNumber ?revNum;   "
			+ "         			 projects:created ?object .  "
			+ " 		?object		 projects:hasId \"%d\" ^^xsd:int ;   		 "
			+ "         			 projects:hasLoadData ?data ;"
			+ "						 rdfs:label \"%s\"^^xsd:string  . "
			+ " 		loadpoint:%s projects:belongsTo ?data ."
			+ "			?data 		 rdfs:label \"%s\" ^^xsd:string ;"
			+ "						 ?relation 	?literalValue ."
			+ " 		?revision2	 projects:hasRevisionNumber ?revNum3;   "
			+ "         			 projects:created ?data .   "  
			+"  		FILTER NOT EXISTS {"
			+ "					 		?otherRevision1 projects:deleted ?data ;"
			+ "                           		 		projects:hasRevisionNumber ?revNum1 . "
			+ "  						FILTER ( ?revNum1 <=  \"%d\"  && ?revNum1 >  \"0\" )"                                         
			+ "   		} "		
			+"  		FILTER NOT EXISTS {"
			+ "					 		?otherRevision2 projects:deleted ?object ;"
			+ "                           		 		projects:hasRevisionNumber ?revNum2 . "
			+ "  						FILTER (?revNum2 <=  \"%d\"  && ?revNum2 >  \"0\"  )"                                         
			+ "   		} "
			+ " 		FILTER( ?revNum <= ?targetRevisionNum && ?revNum > \"0\"  )"
			+ " 		FILTER( ?revNum3 <= ?targetRevisionNum && ?revNum3 > \"0\" )"
			+ "}";

	public static final String FETCH_USERS_PROJECT_REVISION = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "		SELECT DISTINCT ?checkoutRevisionId ?revision"
			+ "			WHERE {projects:%s projects:hasUser ?user ;"
			+ "                     projects:hasRevision ?revision ."
			+ "				   ?user users:hasGid \"%s\" ^^xsd:string."
			+ "                ?revision projects:hasCheckoutRevisionId ?checkoutRevisionId."
			+ "                FILTER NOT EXISTS{?revision projects:hasCheckoutRevisionId \"\" ^^xsd:string"
			+ "                }"
			+ "			}";

	public static final String DELETE_REVISIONS_PROJECT = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "prefix revisions: <http://www.siemens.com/krawalcloud/projects/%s/revisions/>"
			+ "delete{"
			+ "        projects:%s projects:hasUser users:%s ."
			+ "        projects:%s projects:hasRevision revisions:%s ."
			+ "        revisions:%s ?p ?o."
			+ "		   revisions:%s ?relations ?objects ."
			+ "		   ?objects ?e ?f."
			+ "      }"
			+ "where{"
			+ "        projects:%s projects:hasUser users:%s ."
			+ "        projects:%s projects:hasRevision revisions:%s ."
			+ "        revisions:%s ?p ?o."
			+ "		   revisions:%s ?relations ?objects ."
			+ "		   OPTIONAL {?objects ?e ?f}.	"
			+ " }";

	public static final String DELETE_RELATION_PROJECT = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ " delete{"
			+ "			projects:%s projects:hasUser users:%s."
			+ " }"
			+ " where{"
			+ "			projects:%s projects:hasUser users:%s."
			+ " }";

	public static final String FETCH_PROJECT_USERS = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/> "
			+ "		SELECT DISTINCT ?user ?id "
			+ "		WHERE{"
			+ "         projects:%s projects:hasUser ?user ."
			+ " 		?user users:hasGid ?id."
			+ " 		FILTER(?id in (%s))"
			+ " 	}";

	public static final String FETCH_USER_ACCESS_ALL_PROJECTS = "prefix projects: <http://www.siemens.com/krawalcloud/projects/>"
			+ "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "SELECT DISTINCT ?projects"
			+ "		WHERE{ ?projects projects:hasUser users:%s.}";

	public static final String DELETE_USER = "prefix users: <http://www.siemens.com/krawalcloud/users/>"
			+ "DELETE {users:%s ?p ?o}"
			+ "WHERE {users:%s ?p ?o}";

}
